#define	INT 1
#define	CHAR 2
#define	RETURN 3
#define IF 4
#define	ELSE 5
#define	WHILE6
#define	BREAK 7
#define	PRINT 8
#define	READ 9
#define IDENTIFIER 10
#define NUMBER 11
#define ASSIGN 12
#define EXCLAMATION 13
#define ADD 14
#define SUBTRACT 15
#define MULTIPLY 16
#define SLASH 17
#define EQUAL 18
#define NOTEQUAL 19
#define LESS 20
#define GREAT 21
#define LESSEQUAL 22
#define GREATEQUAL 23
#define AND 24
#define OR 25
#define LBRACKET 26
#define RBRACKET 27
#define LPARENTHESIS 28
#define RPARENTHESIS 29
#define LBRACE 30
#define RBRACE 31
#define SEMICOLON 32
#define COMMA 33
#define DOUBLESLASH 34
#define CHARV 35
